repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: ^openapi\.json$
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: no-commit-to-branch
        args: ["--branch=main"]
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: generate-and-diff-openapi-schema
        name: Generate and Assert that OpenAPI Schema is up to date
        entry: >-
          uv run scripts/generate-openapi.py generate-and-diff
            --existing-spec ./openapi.json
            --output-spec ./openapi.json
            --fail-on-diff
        language: system
        files: ^openapi\.json$|^src/.*\.py$
        pass_filenames: false
        always_run: false
